### ISSUE TITLE
Crash on world load/create.

### ISSUE THREAD

**Issue by Thiana** [MysteriousAges/SimpleDim#2]
Reopening #1 since I'm getting the same crash with beta2. Log at http://pastebin.com/Wr7arNbj. Using forge 1492.

**Comment by MysteriousAges** [comment]
You could have actually just re-opened #1. :P

Please post your dimension config file, if you have one.

**Comment by Thiana** [comment]
The dimension config is just a cut and paste of your examples:

Test.cfg

---

customAge { id: 16; type: overworld; spawn: (12, 75, -153); seed: 15203824 }
justAVoid { id: -2; type: void }
justGrassAndSlimes { id: 3; type: superflat; generator: "2;7,2x3,2;1;village" }

---

PS: How do you reopen an issue? It was marked as closed I didnt see an option to reopen?

**Comment by Thiana** [comment]
I was playing with this a little more. It seems that customAge is causing the crash, since justAVoid and justGrassAndSlimes work both alone and together.

**Comment by MysteriousAges** [comment]
It'll be anything that attempts to override the world's seed, since that's the field that it can't access. For some reason it doesn't look like your instance is picking up the access transformer...?

Try running without WAILA, and then NEI/CCC as well.

(The reopen button should appear at the end of a bug thread, next to the "comment" button.)

**Comment by Thiana** [comment]
This appears to be fixed in beta3 since its now working with Waila/NEI/CCC installed.

**Comment by MysteriousAges** [comment]
Okay, cool! Thanks for updating it. (:
